site_name: Árabe I
site_url: http://lamelas.org/arabe/
theme:
    name: material
    custom_dir: theme_overrides/
    logo: img/logo.png
    favicon: img/logo.png
    features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - navigation.top
nav:
    - Alfabeto: alfabeto.md
    - Glossário: glossario.md
    - Programa: programa.md
    - Aulas:
        - Sumários: aulas/index.md
        - Aula 10: aulas/aula10.md
plugins:
    - search
markdown_extensions:
    - smarty
    - tables
extra_css:
    - css/overrides.css
    - css/colors.css
extra_javascript:
    - javascripts/highlight.js
    - javascripts/glossary.js
    - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
    - javascripts/tablesort.js
